<?php

namespace Modules\Api\Controllers;


use App\Http\Controllers\Controller;
use Modules\Car\Models\Car;
use Illuminate\Http\Request;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;

class CarController extends Controller
{
    protected $carClass;
    protected $locationClass;

    public function __construct()
    {
        $this->carClass = Car::class;
        $this->locationClass = Location::class;
    }

    public function callAction($method, $parameters)
    {
        if (!Car::isEnable()) {
            return $this->sendError(__("Car not found"));
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $list = call_user_func([$this->carClass, 'search'], $request);
        $limit_location = 15;
        if (empty(setting_item("car_location_search_style")) or setting_item("car_location_search_style") == "normal") {
            $limit_location = 1000;
        }
        $data = [
            'data' => $list->map(function ($row) {
                return $row->dataForApi();
            }),
            'list_location' => $this->locationClass::where('status', 'publish')->limit($limit_location)->with(['translations'])->get()->toTree(),
            'car_min_max_price' => $this->carClass::getMinMaxPrice(),
        ];
        $data['attributes'] = Attributes::where('service', 'car')->orderBy("position", "desc")->with(['terms' => function ($query) {
            $query->withCount('car');
        }, 'translations'])->get();

        return $this->sendSuccess($data);
    }

    public function detail($slug)
    {
        $row = $this->carClass::where('slug', $slug)->orWhere('id', $slug)->with(['location', 'translations', 'hasWishList'])->first();;
        if (empty($row) or !$row->hasPermissionDetailView()) {
            return $this->sendError('no found');
        }
        $translation = $row->translateOrOrigin(app()->getLocale());
        $car_related = [];
        $location_id = $row->location_id;
        if (!empty($location_id)) {
            $car_related = $this->carClass::where('location_id', $location_id)->where("status", "publish")->take(4)->whereNotIn('id', [$row->id])->with(['location', 'translations', 'hasWishList'])->get();
        }
        $review_list = $row->getReviewList();
        $data = [
            'row' => $row->dataForApi(true),
            'car_related' => $car_related,
            'booking_data' => $row->getBookingData(),
            'review_list' => $review_list,
        ];
        return $this->sendSuccess($data);
    }
}
